from .dashboard import admin_panel
from .courses import (
    course_create,
    course_detail,
    course_update,
    course_delete,
    module_create,
    module_delete,
    module_move,
    content_create,
    content_update,
    content_move,
    content_delete,
    create_exam_for_course,
)
from .users import user_change_role, user_delete
from .paths import (
    path_create,
    path_detail,
    path_update,
    path_delete,
    path_add_course,
    path_remove_course,
    path_move_up,
    path_move_down,
)
from .teams import (
    team_create,
    team_update,
    team_delete,
    team_add_member,
    team_remove_member,
)

__all__ = [
    "admin_panel",
    "course_create",
    "course_detail",
    "course_update",
    "course_delete",
    "module_create",
    "module_delete",
    "module_move",
    "content_create",
    "content_update",
    "content_move",
    "content_delete",
    "create_exam_for_course",
    "user_change_role",
    "user_delete",
    "path_create",
    "path_detail",
    "path_update",
    "path_delete",
    "path_add_course",
    "path_remove_course",
    "path_move_up",
    "path_move_down",
    "team_create",
    "team_update",
    "team_delete",
    "team_add_member",
    "team_remove_member",
]
